In [ ]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4,5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
C = np.dot(A, B)
print(C)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [ ]:
C.max()

np.int64(47)